lms/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'lms'

urlpatterns = [
    path('', home, name="home"),
    path('user_registration', user_registration, name='user_registration'),
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
]

passwordhasher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls')),
]

lms/models.py
from django.db import models

# Create your models here.

lms/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth

def home(request):
    return render(request, 'lms/home.html')

def user_registration(request):
    if request.method == 'POST':
        user_name = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if password1 == password2:
            if User.objects.filter(username = user_name).exists():
                messages.info(request, 'Username taken')
                return redirect('lms:user_registration')
            else:
                user = User.objects.create_user(username = user_name, password = password1)
                user.save()
                return redirect('lms:login')
        else:
            return redirect('lms:user_registration')
    else:
        return render(request, 'lms/user_registration.html')

def login(request):
    if request.method == 'POST':
        user_name = request.POST.get('username')
        password = request.POST.get('password')

        user = auth.authenticate(username = user_name, password = password)

        if user is not None:
            auth.login(request, user)
            return redirect("/")
        else:
            messages.info(request, 'Invalid username and password')
            return redirect('lms:login')
    else:
        return render(request, 'lms/login.html')

def logout(request):
    auth.logout(request)
    return redirect("/")
    

lms/templates/lms/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>GKTCS</title>

    </head>

    <body>

        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'lms:logout' %}">Logout</a>&nbsp;
        {% else %}
        <a class="btn btn-primary" href="/login">Login</a>
        <a class="btn btn-primary" href="/user_registration">Signup</a>
        {% endif %}

    </body>
    </html>

lms/templates/lms/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Login</title>

    </head>

    <body>
        <h1>Login</h1>
        <form action="login" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required><br>
            <input type="text" name="password" placeholder="Password" required><br>
            <input type="Submit">
        </form>

        <div>
            {% for message in messages %}
                <h3>{{message}}</h3>
            {% endfor %}
        </div>
    </body>
    </html>

lms/templates/lms/user_registration.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Registration</title>

    </head>

    <body>
        <h1>Signup</h1>
        <form action="user_registration" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required><br>
            <input type="text" name="password1" placeholder="Password" required><br>
            <input type="text" name="password2" placeholder="Confirm password" required><br>
            <input type="Submit">
        </form>

        <div>
            {% for message in messages %}
                <h3>{{message}}</h3>
            {% endfor %}
        </div>
    </body>
    </html>